### ISSUE TITLE
Why don't you use absl::Hash by default here?

### ISSUE THREAD

**Issue by MrJia1997** [google/quiche#10]
https://github.com/google/quiche/blob/5b786dfeb069f03bad6cde7efeedbe643f4f0c84/common/quiche_linked_hash_map.h#L39

Hi there, recently I was reading the source code of `quiche`, and this line confused me a bit. I wonder why you don't use `absl::Hash` by default instead of `std::hash`, since `std::hash` may not have the high entropy in most significant bits that `absl::node_hash_map` needs? Thank you!

**Comment by bencebeky** [comment]
Thank you for reporting this issue.  It has been fixed at https://github.com/google/quiche/commit/e266d932c211971d4ba0cebe20875a139749e6b8.
