### ISSUE TITLE
Prioritization support

### ISSUE THREAD

**Issue by NooshinEghbal** [google/quiche#17]
Does quiche have any prioritization support? Either the three-based ones or the recent [Extensible Prioritization Scheme](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-priority-03.txt)?

**Comment by bencebeky** [comment]
For HTTP/2, QUICHE only implements wire level serialization and framing, it does not do actual prioritization of streams.  It does support serialization and framing of both HTTP/2-style dependency+weight in HEADERS and PRIORITY frames, and PRIORITY_UPDATE frames.  See quiche/http2/decoder/payload_decoders/priority_update_payload_decoder.h, and SerializePriorityUpdate() in quiche/spdy/core/spdy_framer.h.

For HTTP/3, QUICHE only supports PRIORITY_UPDATE frames, see SetPriority() and MaybeSendPriorityUpdateFrame() in quiche/quic/core/quic_stream.h.  quiche/quic/core/quic_write_blocked_list.h takes care of ordering the writes according to priorities.

**Comment by bencebeky** [comment]
> Do you mean the priority of streams or the resource priority? I was asking about the second one and if the client can specify urgency/incremental priority scores for each request so the server would schedule data transmission based on those priorities like [Extensible Prioritization Scheme](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-priority-03.txt).

Yes, the client can specify urgency using QuicStream::SetPriority() for HTTP/3, and the client can send dependency/weight in HTTP/2.  Note that the incremental bit is currently unimplemented.

**Comment by NooshinEghbal** [comment]
Hello,

Thanks for your reply.

I have an idea to improve page load time over QUIC. We recently published a
short paper on this idea in ANRW and got positive reviews.
I also talked to Ian Swett and he thought it is worth implementing over
QUIC but unfortunately I could not start the internship process at the
right time for this summer.
Are you interested in collaborating on this project? I can send you the
ANRW paper if you are interested.

Thanks,
Nooshin

**Comment by ianswett** [comment]
Bence is a team member of mine and I would support him or anyone else on my
team working with you.  If you are still interested in figuring out a plan
for an internship, please email me directly and I'll see if I can figure
something out.

Thanks, Ian

**Comment by NooshinEghbal** [comment]
Hi Ian,

Thanks for your reply.
I sent an email to you with the title "Summer Internship query" on June 2
but have not heard back.

**Comment by ianswett** [comment]
Maybe it was misfiled, I'll search for it now.

**Comment by NooshinEghbal** [comment]
Thanks.
