### ISSUE TITLE
Unable to use SSLKEYLOGFILE option

### ISSUE THREAD

**Issue by deshmukhrajvardhan** [google/quiche#2]
As i wanted to look at the decrypted packets using wireshark, i tried using the below:

`export SSLKEYLOGFILE=<quic_keylog_file>`, which should work for boring ssl
https://github.com/google/boringssl/search?q=SSLKEYLOGFILE&type=code

But it didn't work and i didn't get the keylog file.

Should we change the cmake file to include boringssl `tool/client.cc` to make it work and obtain SSLKEYLOGFILE?

**Comment by bencebeky** [comment]
Which QUICHE embedder are you using?  QUICHE does not run on its own and does not have a cmake file.  I'm asking because I assume Chrome supports $SSLKEYLOGFILE with QUIC (though I might be mistaken), so in order to make this work for your case the change might need to happen outside of QUICHE.

**Comment by deshmukhrajvardhan** [comment]
Thanks you for the super-fast response!

Ah, I'm sorry about the mention of cmake. I was using https://github.com/bilibili/quiche 

Bit of a background, i wanted to test the masque implementation (server-client and look at the decrypted packets), which is available on only chromium (not envoy according to the build file).

Are there build instruction on building/running the server client via terminal (headless), and also setting the SSLKEYLOG?

**Comment by deshmukhrajvardhan** [comment]
Found a way to do it https://github.com/bilibili/quiche/issues/8
Thanks!
