### ISSUE TITLE
Streams with the same priority use round robin to write data

### ISSUE THREAD

**Issue by slusnys** [google/quiche#25]
It seems to me that when there is multiple streams with the same priority, then the implemented algorithm still uses round-robin to choose the one that will actually write. However, this is not what RFC 9218 suggests, unless "incremental" parameter is provided (which is not supported at the moment). I am not sure if this behaviour is actually a bug, or if it is intended deviation from the RFC.

There is a soft limit (16k) implemented:
https://quiche.googlesource.com/quiche/+/refs/heads/main/quiche/quic/core/quic_write_blocked_list.cc#56

Then, when a stream is being added to the list of write blocked stream, it is added to the front or to the back of the list,
see QuicWriteBlockedList::AddStream().

If the stream is pushed to the end, then the other streams with the same priority will write at the next writing opportunity, instead of the stream that is being added.

**Comment by bencebeky** [comment]
Thank you for bringing up this issue.  This behavior of QUICHE is not intentional, and I agree that it should be fixed.

**Comment by bencebeky** [comment]
The spec says serve requests round-robin if incremental, one-by-one if not, and the default is not incremental.  QUICHE currently ignores the incremental bit and always does round-robin.  While I agree that always doing one-by-one would be an improvement over this, I'm actually planning to implement what the spec says.  Parsing and pumbing of the incremental bit is almost done:

https://github.com/google/quiche/commit/ec077d42010aa1a40a8c7c8bf1d84409add89b7d
https://github.com/google/quiche/commit/ebbdaae9eaf724e89aa3ee0d0b61005da0d09d6b
https://github.com/google/quiche/commit/ab43084988b8ca73d30374b7030057fa18019589
https://github.com/google/quiche/commit/bb8ac619a1e6563a94cf2abd0e59df9d795fa8a3
https://github.com/google/quiche/commit/caad3de72b432483f921af0717fb561e8c03b1b4
https://github.com/google/quiche/commit/28e5246e217c35e5c3565d4b6ab03a5ff2da6281
https://github.com/google/quiche/commit/2be9d500f92536c1bba99fbe619d1af63549f1ab

**Comment by slusnys** [comment]
Thanks for taking care of this!
I've looked at the latest QUICHE code and although there has been a lot of work done already, it seems  that QUICHE still ignores the incremental bit. Please, update this thread once it is implemented. Thanks!

**Comment by bencebeky** [comment]
Two related commits landed recently that change behavior gated behind a default-false flag each: https://github.com/google/quiche/commit/0020a2213f74142f9484768007496adba003bb6a and https://github.com/google/quiche/commit/7e67f01d296f9a57f63ca41af665f7b354078772.  The first one disables round-robin for non-incremental streams, and the second one disables the 16 kB batch writes and instead makes writes immediate round-robin (for all streams if the first flag is false, for incremental streams only if the first flag is true).
