### ISSUE TITLE
Any version release?

### ISSUE THREAD

**Issue by fredgan** [google/quiche#27]
Hi all,
  I find this project has been some years, but has no releases or tags. Can this project release a version? Thanks a lot!

**Comment by RyanTheOptimist** [comment]
Thanks for asking. We have no plans to do versioned releases. QUICHE consumers are expected to build from HEAD.

**Comment by fredgan** [comment]
But I wonder why? Is this project unmatured? It's highly recommended in OpenSSF best practice. OpenSSF is securing Open Source Projects. https://openssf.org

**Comment by DavidSchinazi** [comment]
The project is mature. However our deployment policy is to keep the tip of tree in good shape as opposed to performing testing on occasional commits. We don't have any way or reason to say that a commit is more special than another.
