### ISSUE TITLE
how to build on window?

### ISSUE THREAD

**Issue by 516025** [google/quiche#40]
ERROR: C:/users/user/_bazel_user/rwpuuipt/external/zlib/BUILD.bazel:7:11: Compiling uncompr.c failed: (Exit 2): cl.exe failed: error executing command (from target @zlib//:zlib) D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 26 arguments skipped)
cl: 命令行 error D8021 :无效的数值参数“/Wno-narrowing”
Target //quiche:quiche_core failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 231.785s, Critical Path: 13.94s
INFO: 202 processes: 37 internal, 165 local.

**Comment by vasilvv** [comment]
We currently don't support Windows, at least for the full Bazel build.  This is something that we do have plans to support in the future (the quiche_core code is compiled on Windows in Chrome), but no specific timeline at this point.

**Comment by 516025** [comment]
> We currently don't support Windows, at least for the full Bazel build. This is something that we do have plans to support in the future (the quiche_core code is compiled on Windows in Chrome), but no specific timeline at this point.

thanks！！

**Comment by martenrichter** [comment]
You may want to look at my webtransport node.js addon:
https://github.com/fails-components/webtransport
there I have some CMake files and additional patches to get it to build for windows.
Or my now a bit outdated PR:
https://github.com/google/quiche/pull/32
anyway, it is possible to get it to build on windows. The hardest point are the dependencies like protobuf etc., but there you can look into my CI/CD jobs for the windows build of the addon.
