### ISSUE TITLE
Update Platform Implementations Links in README

### ISSUE THREAD

**Issue by MrJia1997** [google/quiche#9]
When I click on the link about platform implementations in README, it shows that "The file does not exist at this commit". Does it mean that those links in the README are outdated? It is welcome to submit a PR to fix this? Thank you.

**Comment by bencebeky** [comment]
Thank you for reporting this issue.  It turns out there was a bug in the logic that does include path replacement for source files and it mistakenly applied to README.md.  I fixed it.
